version: '3'

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
services:
  controller:
    image: ddb:latest
    container_name: controller
    hostname: controller
    environment:
      - DEPLOY_MODE=controller
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/controller/master:/data/ddb/server/master
      - ./cluster/controller/log:/data/ddb/server/log
      - ./config/controller.cfg:/data/ddb/server/config/controller.cfg
      - ./config/cluster.cfg:/data/ddb/server/config/cluster.cfg
      - ./config/cluster.nodes:/data/ddb/server/config/cluster.nodes
    ports:
      - "19000:8888"
    networks:
      dbnet:
        ipv4_address: 10.5.0.100

  agent1:
    image: ddb:latest
    container_name: agent1
    hostname: agent1
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "19001:19001"
    volumes:
      - /hdd/hdd1/dolphindb/server1/log:/data/ddb/server/log
      - /hdd/hdd1/dolphindb/server1/P1-agent:/data/ddb/server/P1-agent
      - /hdd/hdd1/dolphindb/server1/P1-node1:/data/ddb/server/P1-node1
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./config/agent1.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data2:/data2
      - /mnt/data/data1:/data3
    networks:
      dbnet:
        ipv4_address: 10.5.0.2

  agent2:
    image: ddb:latest
    container_name: agent2
    hostname: agent2
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes: 
      - /hdd/hdd2/dolphindb/server2/log:/data/ddb/server/log
      - /hdd/hdd2/dolphindb/server2/P2-agent:/data/ddb/server/P2-agent
      - /hdd/hdd2/dolphindb/server2/P2-node1:/data/ddb/server/P2-node1
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./config/agent2.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd2/data2:/data2
      - /mnt/data/data2:/data3
    ports:
      - "19002:19001"
    networks:
      dbnet:
        ipv4_address: 10.5.0.3
