version: "3.7"

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16

services: 
    node1:
        image: yandex/clickhouse-client:latest
        container_name: client1
        hostname: client1
        volumes: 
            - /hdd/hdd1/data:/data
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "19001:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.2

    node2:
        image: yandex/clickhouse-client:latest
        container_name: client2
        hostname: client2
        volumes: 
            - /hdd/hdd2/data:/data
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "19002:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.3