version: "3.7"

volumes: 
    - /etc/clickhouse-server:/etc/clickhouse-server
    - /etc/metrika.xml:/etc/metrika.xml
    - /var/log/clickhouse-server/:/var/log/clickhouse-server/

services: 
    node1:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18600:8123"
            - "18601:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.1
    node2:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18602:8123"
            - "18603:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.2
    node3:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18604:8123"
            - "18605:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.3   
    node4:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18606:8123"
            - "18607:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.4
    node5:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18608:8123"
            - "18609:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.5
    node6:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18610:8123"
            - "18611:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.6
    node7:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18612:8123"
            - "18613:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.7
    node8:
        image: clickhouse-server:19.4.4.33
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports: 
            - "18614:8123"
            - "18615:9000"
        networks: 
            dbnet:
                ipv4_address: 10.5.0.8

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16