version: '3'

services:
  ddbcontroller:
    image: ddb:latest
    container_name: ddbcontroller
    environment:
      - DEPLOY_MODE=controller
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/controller/master:/data/ddb/server/master
      - ./cluster/controller/log:/data/ddb/server/log
      - ./config/controller.cfg:/data/ddb/server/config/controller.cfg
      - ./config/cluster.cfg:/data/ddb/server/config/cluster.cfg
      - ./config/cluster.nodes:/data/ddb/server/config/cluster.nodes
      - /hdd/hdd1/data:/data2
    ports:
      - "9999:8888"
    networks:
      dbnet:
        ipv4_address: 10.5.0.100

  ddbagent1:
    image: ddb:latest
    container_name: ddbagent1
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/server1/log:/data/ddb/server/log
      - ./cluster/server1/P1-agent:/data/ddb/server/P1-agent
      - ./cluster/server1/P1-node1:/data/ddb/server/P1-node1
      - ./cluster/server1/P1-node2:/data/ddb/server/P1-node2
      - ./config/agent1.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data:/data2
    networks:
      dbnet:
        ipv4_address: 10.5.0.2

  ddbagent2:
    image: ddb:latest
    container_name: ddbagent2
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft:
         -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/server2/log:/data/ddb/server/log
      - ./cluster/server2/P2-agent:/data/ddb/server/P2-agent
      - ./cluster/server2/P2-node1:/data/ddb/server/P2-node1
      - ./cluster/server2/P2-node2:/data/ddb/server/P2-node2
      - ./config/agent2.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data:/data2
    networks:
      dbnet:
        ipv4_address: 10.5.0.3

  ddbagent3:
    image: ddb:latest
    container_name: ddbagent3
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/server3/log:/data/ddb/server/log
      - ./cluster/server3/P3-agent:/data/ddb/server/P3-agent
      - ./cluster/server3/P3-node1:/data/ddb/server/P3-node1
      - ./config/agent3.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data:/data2
    networks:
      dbnet:
        ipv4_address: 10.5.0.4

  ddbagent4:
    image: ddb:latest
    container_name: ddbagent4
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/server4/log:/data/ddb/server/log
      - ./cluster/server4/P4-agent:/data/ddb/server/P4-agent
      - ./cluster/server4/P4-node1:/data/ddb/server/P4-node1
      - ./config/agent4.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data:/data2
    networks:
      dbnet:
        ipv4_address: 10.5.0.5

  ddbagent5:
    image: ddb:latest
    container_name: ddbagent5
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/server5/log:/data/ddb/server/log
      - ./cluster/server5/P5-agent:/data/ddb/server/P5-agent
      - ./cluster/server5/P5-node1:/data/ddb/server/P5-node1
      - ./config/agent5.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data:/data2
    networks:
      dbnet:
        ipv4_address: 10.5.0.6

  ddbagent6:
    image: ddb:latest
    container_name: ddbagent6
    environment:
      - DEPLOY_MODE=agent
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config/dolphindb.lic:/data/ddb/server/dolphindb.lic
      - ./cluster/server6/log:/data/ddb/server/log
      - ./cluster/server6/P6-agent:/data/ddb/server/P6-agent
      - ./cluster/server6/P6-node1:/data/ddb/server/P6-node1
      - ./config/agent6.cfg:/data/ddb/server/config/agent.cfg
      - /hdd/hdd1/data:/data2
    networks:
      dbnet:
        ipv4_address: 10.5.0.7

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
